### ISSUE TITLE
Price impact is different on Swap form and Confirmation modal

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#1360] opened 2021-08-30 12:20 UTC
Reproducible in Prod/Stage/Barn

**Steps**: 
Open Swap page in regular mode
Fill in tokens to swap
Specify an amount to swap (in this case price impact matches)
Wait till prices are updated (in 30 sec)
Verify price impact on the Swap form and on the Confirmaiton modal

**AR**: values are different
![impact confirm.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/dffb41a1-fdcd-43e4-a960-fb42ec0ca74d)
![impact swap.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c0ab6c88-112c-4e8a-b5c3-8e84a04a24a2)

**ER**: values are the same

**Comment by alfetopito** [comment] 2021-08-30 16:46
I'd say to try out after the fix for #999 is merged.
I suspect this is because the USD estimation is actually different in both moments, but the difference is so small that due to rounding the USD amounts didn't change.

Unless you are able to reproduce with price impact difference greater than 0.1% while USD prices remain the same.

**Comment by elena-zh** [comment] 2021-08-30 17:22
@alfetopito , the issue is reproducible in #1315:
![999-1](https://user-images.githubusercontent.com/70885163/131379157-d1215bce-1375-40df-9178-0c7e1a1a383a.jpg)
![999](https://user-images.githubusercontent.com/70885163/131379171-b8bcdcb2-1f83-4855-9cc1-dfa2ba32931d.jpg)

**Comment by alfetopito** [comment] 2021-08-30 18:21
Is this case, it still looks like the USD price estimation for WETH changed between the form and the confirmation.
On the first you have `97.78` while on the confirmation you have `97.84`.

In that case I see no problem as the impact is based on both tokens USD values relative to each other:

1. form: `1 - (97.78 / 97.42) * 100 = 0.369534 %`
2. confirmation: `1 - (97.84/97.42) * 100 = 0.431123%`

If it happens that you have the same USD values and price impact is different than it could be a problem.

**Comment by elena-zh** [comment] 2021-08-31 09:29
Thank you for explanation!
Then, my question is why do we get different From amount USD estimations on the Swap form and Confirm modal?
https://drive.google.com/file/d/1lcslLIcw39LxnL6CJw5vTulgetkCkezq/view

**Comment by alfetopito** [comment] 2021-08-31 20:40
Then this is something we need to investigate further.
I've mentioned in a slack thread as it could be related to the issue David reported.
Not entirely sure.

**Comment by elena-zh** [comment] 2021-09-30 11:40
The issue is no longer reproducible.
I'm closing it.

**Closed** 2021-09-30 11:40 UTC
Labels: 🐞 Bug, app:CowSwap, ❗️Medium
