### ISSUE TITLE
Balances are not detected when switching between ETH/WETH to WETH/ETH

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1428] opened 2021-09-10 11:28 UTC
**Description**
When switching between wrap and unwrap the prior inserted values or balances are not correctly detected.

**How to Reproduce**
1. Go to cowswap
2. Chose ETH as sell and WETH as buy token
3. Insert value to wrap/unwrap within your balance
4. Click switching arrow

**Expected behavior**
Should detect that the user has enough balance

**Screenshots**

https://user-images.githubusercontent.com/34510341/132846670-3ad07728-3567-4797-b5ab-d6561c6a311b.mov

**Comment by elena-zh** [comment] 2021-09-10 11:32
I will link #928 issue with the current one: it is not a duplicate, but they might be related.

**Comment by elena-zh** [comment] 2021-09-21 10:39
The same is for xDAI/WXDAI

**Comment by elena-zh** [comment] 2021-09-30 11:50
The issue is no longer reproducible. 
I'm closing it.

**Closed** 2021-09-30 11:50 UTC
Labels: 🐞 Bug, app:CowSwap, ❗️Medium
