### ISSUE TITLE
[CowSwap-SafeMobile]No CowSwap icon after connection to the safe  in the ios mobile app

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/cowswap#2003] opened 2021-12-16 11:48 UTC
**Description**
No CowSwap icon after connection to the safe  in the ios mobile app

**How to Reproduce**
1. Go to ios safe mobile app
2. Open dApps on rinkeby safe
3.Connect to CowSwap app
Current result: No icon for CowSwap in connected apps list
4. Create tx and check details of create tx in ios safe app
Current result: No icon of CowSwap

**Expected behavior**
the app should have correct icon

**Screenshots**
![image](https://user-images.githubusercontent.com/338622/146366075-a0b1ac76-a7e0-42e4-a917-2b7cb6d3a1f0.png)
![image](https://user-images.githubusercontent.com/338622/146366119-df4c4a8f-9d4a-479f-8d8e-ec229ecf040d.png)

**Additional context**
ios safe app version 3.5.0 
iPhone 11/14.8

**Comment by elena-zh** [comment] 2021-12-16 11:53
Duplicate of #1792

**Closed** 2021-12-16 12:06 UTC
