### ISSUE TITLE
Label cancelled transactions as Cancelled

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1435] opened 2021-09-15 10:51 UTC
**Description**
If a user cancels a transaction (Approve/ unwrap/wrap) it simply disappears from the recent history. 
Eventhough the user is aware of this process as their confirming this process. It might be good to show this in the recent activities history. 

Currently it is displayed like this: 
<img width="557" alt="Bildschirmfoto 2021-09-15 um 12 45 40" src="https://user-images.githubusercontent.com/34510341/133420106-da07ac7f-52bb-44f6-aefe-86dbc2c89a83.png">
<img width="550" alt="Bildschirmfoto 2021-09-15 um 12 46 04" src="https://user-images.githubusercontent.com/34510341/133420323-c01c05a8-be2b-42ca-af9c-831748b7af9b.png">

**Proposal**

Label it as done for canceling an order: 

<img width="493" alt="Bildschirmfoto 2021-09-15 um 12 48 16" src="https://user-images.githubusercontent.com/34510341/133420262-eba9c2d6-7b20-410a-a172-1a82d7ce0d01.png">

<img width="491" alt="Bildschirmfoto 2021-09-15 um 12 49 14" src="https://user-images.githubusercontent.com/34510341/133420332-406ffa03-b978-425c-9fdd-bef81c9e99e4.png">

**Additional context**
Connected to #1302 (#584) and related to #1374

**Comment by elena-zh** [comment] 2021-09-20 10:13
Might be a duplicate of #1382

**Closed** 2021-11-24 13:39 UTC
Labels: ☀️ Enhancement, app:CowSwap, ⬇ Low, Protofire
