### ISSUE TITLE
Wrong USD estimation for DAI in most recent PR

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1363] opened 2021-08-31 09:53 UTC
**Description**
I came across this in a few open PRs. 
The Dai USD estimation is quite off

**How to Reproduce**
1. Open a new PR e.g. https://pr1361--gpswapui.review.gnosisdev.com/#/swap.'
2. Chose DAI as a from token and insert a value
3. Observe USD estimation

**Expected behavior**
Should be around $1

**Screenshots**
<img width="1436" alt="Bildschirmfoto 2021-08-31 um 11 51 46" src="https://user-images.githubusercontent.com/34510341/131482066-f0495f4a-64ed-4d9b-a558-b9a0db20ea9f.png">

**Comment by elena-zh** [comment] 2021-08-31 10:23
Yes, the same I noticed in #1356 pr. 
It causes the next issue: when I swap a token pair with DAI from 'To' token to 'From', I get it's amount recalculated as `<0.0001`
https://drive.google.com/file/d/1fTZHOmceqjO2RjqKw2-WxwxKk4cq76ww/view

**Comment by MareenG** [comment] 2021-08-31 10:36
Now also experienced this for DAI as TO token 

:money_with_wings::money_with_wings::money_with_wings:
<img width="590" alt="Bildschirmfoto 2021-08-31 um 12 32 16" src="https://user-images.githubusercontent.com/34510341/131488007-bbfaf88f-3a13-4187-8eaa-3ea4762e26b4.png">

**Comment by MareenG** [comment] 2021-08-31 10:39
<img width="599" alt="Bildschirmfoto 2021-08-31 um 12 38 27" src="https://user-images.githubusercontent.com/34510341/131488371-ead8fee5-8f32-46f8-b3cb-fcc45c95e9c3.png">
<img width="525" alt="Bildschirmfoto 2021-08-31 um 12 38 39" src="https://user-images.githubusercontent.com/34510341/131488373-6c9f7c06-c389-4d85-8ac4-87adc3b717dc.png">

**Comment by elena-zh** [comment] 2021-09-30 11:46
The issue is no longer reproducible to me. 
I'm closing it

**Closed** 2021-09-30 11:46 UTC
Labels: 🐞 Bug, app:CowSwap, ❗️Medium
