### ISSUE TITLE
[Mobile]- Network not displayed XDai/Rinkeby

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1168] opened 2021-08-04 07:52 UTC
**Description**
If you access Cowswap on  a mobile device or reduced screen size the network is not displayed

**How to Reproduce**
1. Go to Cowswap on a mobile device or with a reduced size
2. Click on Connect wallet
3. Change to Rinkeby or XDai
4. See that the network is not displayed

**Expected behavior**
If the network if not mainnet it should be displayed also for reduced screen size. 
I guess this is lost as the header/ footer size is limited but it still should be displayed IMO

**Screenshots**
Reduced Size: 
<img width="630" alt="Bildschirmfoto 2021-08-04 um 09 48 26" src="https://user-images.githubusercontent.com/34510341/128142891-d4447d34-e328-4f61-8e1c-ff18018c8b12.png">
<img width="628" alt="Bildschirmfoto 2021-08-04 um 09 48 39" src="https://user-images.githubusercontent.com/34510341/128142902-9687bf94-7caf-4faf-92ba-debd877c15f3.png">

Wide screen : 
<img width="632" alt="Bildschirmfoto 2021-08-04 um 09 50 53" src="https://user-images.githubusercontent.com/34510341/128143033-1757297c-3190-4c51-8bd2-724425fb078c.png">

**Comment by alfetopito** [comment] 2021-08-04 18:07
Duplicate of https://github.com/gnosis/cowswap/issues/729?

Actually this one has a better description, I'm in favor of closing that and keeping this one

**Comment by elena-zh** [comment] 2021-08-06 10:23
Actually, network indicator stops to be displayed when screen width is less than 720 px. 
However, when screen width is greater that 720, it is displayed, but there is no padding between an account info and this indicator
![image](https://user-images.githubusercontent.com/70885163/128496566-6f009b3b-1789-4a02-bf18-0d5a53396ec8.png)

It would be great to fix both of this issues in this ticket, I think.

**Comment by elena-zh** [comment] 2021-08-18 12:03
>  but there is no padding between an account info and this indicator

fixed in #1269

**Comment by elena-zh** [comment] 2021-11-10 08:11
The issue is no longer relevant as a new network switcher was added to the app

**Closed** 2021-11-10 08:11 UTC
Labels: 🐞 Bug, app:CowSwap, ❗️Medium
