### ISSUE TITLE
[v0.17] USD estimation missing in price section 

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#1095] opened 2021-07-29 07:56 UTC
**Description**
If you change the price display from TokenA=TokenB to TokenB=TokenA the USD estimation is not always displayed

**How to Reproduce**
1. Go to https://pr1075--gpswapui.review.gnosisdev.com/#/swap
2. Chose a token pair and enter swap amount
3. Scroll down to price click on the arrow next to PRICE 

**Expected behavior**
USD estimation should be displayed for both options

**Screenshots**
<img width="440" alt="Bildschirmfoto 2021-07-29 um 09 49 39" src="https://user-images.githubusercontent.com/34510341/127453427-1759303e-cea2-440c-b807-d7c9ce0a5920.png">
<img width="437" alt="Bildschirmfoto 2021-07-29 um 09 49 32" src="https://user-images.githubusercontent.com/34510341/127453430-e3ebfd5f-b8e5-4b86-8f18-c7b43ae0d1ed.png">

**Additional context**
Sometimes it just needs a second until it is loaded but in the example above the USD estimation was not shown

**Comment by elena-zh** [comment] 2021-07-29 09:51
I will link this issue with #1091  and #1104 : they might be connected

**Comment by alfetopito** [comment] 2021-07-29 16:11
Yep, I'd say duplicate of https://github.com/gnosis/cowswap/issues/1104.
Well actually this one came first, but we already started dissing it there. I'll close in favor of that one.

**Closed by alfetopito** 2021-07-29 16:11 UTC
Labels: bug, cowswap-app
