### ISSUE TITLE
[Mobile]: Terms and conditions/FAQ do not show content from the top of the page when scroll pages before opening them

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#874] opened 2021-07-06 15:58 UTC
Terms and conditions/FAQ do not show content from the top of the page when scroll pages before opening them

To Reproduce: 
1. Open FAQ page, scroll down to the bottom
2. Then open 'Terms and Conditions page

**AR**: the page is opened and show content at the bottom
https://drive.google.com/file/d/1HfSc4sTFoH4eVVUjj7TjPTThNi58TNxY/view

**ER**: the page shows its content from the top

**Comment by alfetopito** [comment] 2021-07-06 18:07
Duplicate of https://github.com/gnosis/cowswap/issues/650

**Closed by alfetopito** 2021-07-06 18:07 UTC
Labels: bug, cowswap-app
