### ISSUE TITLE
FAQ internal links are not shareable

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#650] opened 2021-05-19 10:07 UTC
**Describe the bug**
FAQ internal links are not shareable, because it doesn't do the scrolling to specific question just by accessing an internal link.

**How to Reproduce**
1. Go to https://cowswap.exchange/#/faq#why-is-cowswap-able-to-offer-gas-free-trades
2. Observe that it didn't scroll

**Expected behavior**
Scrolls automatically to the question

**Additional context**
This is important for two important things:
- Support: Useful to be able to reply users in chats, and support email by sharing a link to the FAQ
- Open FAQ in blank pages: sometimes we might want to open the FAQ in an specific question without breaking the user's workflow. For example, if he is trading, and we show an error or warning, we might want to open a new tab to show more context instead of navigating (so he doesn't lose the context of the trade)

**Comment by W3stside** [comment] 2021-05-19 10:52
happening because `HashLink` is unmounted on tab change thus wiping scroll logic listener. Will need to access the history props and use a hook or similar to keep track.

**Comment by elena-zh** [comment] 2021-08-06 14:40
Duplicate of #1170 , #787 ?

**Comment by elena-zh** [comment] 2021-11-04 15:18
Closed as the issue is a duplicate of #787 and #1170

**Closed** 2021-11-04 15:18 UTC
Labels: 🐞 Bug, app:CowSwap, ⬇ Low
