### ISSUE TITLE
Stuck when switching between networks

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#552] opened 2021-04-28 08:03 UTC
**Describe the bug**
When changing the network in the MM browser the website gets stuck until one refreshes the website

**How to Reproduce**
1. Open MM on mobile to go browser and then insert Cowswap url
2. change network (e.g. Mainnet to Rinkeby)
3. Go back to the browser
4. The trade overview does not appear until one clicks on the home button or SWAP

**Expected behavior**
The whole website should load.

**Screenshots**
Stuck on this screen until you reload
![1619596876811](https://user-images.githubusercontent.com/34510341/116368609-ca2bb980-a808-11eb-917f-5e7ec4ed83e1.jpg)

**Comment by elena-zh** [comment] 2021-08-18 11:22
Might be a duplicate of #1223

**Comment by MareenG** [comment] 2021-08-19 14:14
Duplicating myself 🤦‍♀️

**Closed** 2021-11-23 12:38 UTC
Labels: 🐞 Bug, app:CowSwap, 📱Mobile
