### ISSUE TITLE
Network information missing

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#861] opened 2021-07-06 09:16 UTC
**Description**
The network information is missing for reduced screens

<img width="1060" alt="Bildschirmfoto 2021-07-06 um 11 09 14" src="https://user-images.githubusercontent.com/34510341/124575219-7f9f6c80-de4b-11eb-9a18-8901f2fdf977.png">
<img width="708" alt="Bildschirmfoto 2021-07-06 um 11 09 02" src="https://user-images.githubusercontent.com/34510341/124575236-8201c680-de4b-11eb-8050-af36bef02d22.png">

Might be the same on mobile but my MM keeps crashing so I couldn't test it

**Comment by elena-zh** [comment] 2021-07-06 15:50
@MareenG , the issue is reproducible on Mobile as well.
https://drive.google.com/file/d/1X-AuVex9mh1cs-04gNDxWB1VZWi_LVo2/view

**Comment by alfetopito** [comment] 2021-07-06 18:04
Duplicate of https://github.com/gnosis/cowswap/issues/729

**Closed by alfetopito** 2021-07-06 18:04 UTC
Labels: bug, cowswap-app
