### ISSUE TITLE
Expiration time 1min is broken 

### ISSUE THREAD

**Issue by MareenG** [gnosis/cowswap#854] opened 2021-07-05 13:23 UTC
**Description**
The expiration time of 1 min doesn't work anymore. 
You get an error message no matter how fast you confirm the swap

**How to Reproduce**
1. Go to 'cowswap
2. Set expiration time to 1min
3. Do a trade
4. You get the following error message
<img width="397" alt="Bildschirmfoto 2021-07-05 um 15 19 29" src="https://user-images.githubusercontent.com/34510341/124477805-bc645880-dda4-11eb-86fe-6f514474efe2.png">

**Expected behavior**
If the user needs less than 1 min to sign the swap this error message should not show up.

**Comment by alfetopito** [comment] 2021-07-05 18:20
I think that's a backend limitation.
What we could do maybe is to enforce at least 2 min expiration.

cc @fleupold

**Comment by fleupold** [comment] 2021-07-05 18:43
Wouldn't that make things worse? What we enforce is that the deadline of the trade is at least 1minute in the future (because it will take us some time to batch, solve and execute it) and we don't want to fail a transaction because of "order expired". 

If you chose the default deadline (20min) things should work. Maybe the frontend should also prevent too short deadlines from being entered manually?

**Comment by MareenG** [comment] 2021-07-06 08:27
I just noticed it because in older versions it was possible to go for 1min transaction deadlines. Yes longer transaction deadlines work fine.
If we need more time to batch, solve and execute the transactions we should not allow a 1min transaction deadline in the frontend.

**Comment by biocom** [comment] 2021-07-06 15:46
@fleupold So a more feasible extreme minimum expiry time would be 2 min? Can still see someone wanting this. Do agree that we should enforce 1+ min. inputs on the front-end.

**Comment by fleupold** [comment] 2021-07-09 09:31
It depends on how long the user is looking at the order before sending it. In the moment it reaches our API the expiration date needs to be 1minute in the future. But I'd assume 1minute is fine for that.

**Comment by elena-zh** [comment] 2021-07-30 13:15
Still reproducible in v.0.17. 
However, when I set transaction time as `1.1` min, transaction works fine

**Comment by alfetopito** [comment] 2021-07-30 15:57
Yeah that has not been worked on yet

**Comment by elena-zh** [comment] 2022-02-24 11:09
I'm closing the issue due to min possible TX time is changes to 2 min.

**Closed by elena-zh** 2022-02-24 11:09 UTC
Labels: 🐞 Bug, app:CowSwap, ❗️Medium
