### ISSUE TITLE
Show the current network in the error of no tokens

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#1888] opened 2021-11-18 20:33 UTC
**Description**
![image](https://user-images.githubusercontent.com/2352112/142492016-5171d0f0-41a9-4963-a12c-3ef37ba62ec8.png)

Sometimes users don't find tokens by address, and they don't realise that the reason is because they are not in the right network.

I would suggest that  if we look by address, and we don't find anything we show:
`No tokens found with this address in XXXX network`

Where XXXX is the current network. This way, if you are in xDAI and you input a mainnet address, you will understand the issue.

Also, if you look for symbol, I would use the message:
`No tokens found with this symbol/name, try to search by their Ethereum address`

**Comment by elena-zh** [comment] 2021-11-19 08:24
Seems to be a duplicate of #1088, but I will close that one as the current task has better description.

**Closed** 2021-12-01 15:16 UTC
Labels: ☀️ Enhancement, app:CowSwap, ❗️Medium
